-- DAP setup for C++ files.
-- TODO: https://github.com/mfussenegger/nvim-dap/discussions/1010
-- FIX: DAP C++

-- local dap = require 'dap'
-- local shell = require 'nvim-treesitter.shell_command_selectors'
--
-- local cmd = shell.select_executable {
--     'lldb-dap-18',
--     'lldb-dap',
-- }
--
-- if cmd == nil then
--     error 'No lldb-dap executable found!'
-- end
--
-- dap.adapters.lldb = {
--     type = 'executable',
--     command = cmd,
--     name = 'lldb',
-- }
--
-- dap.configurations.cpp = {
--     {
--         name = 'Launch',
--         type = 'lldb',
--         request = 'launch',
--         program = function()
--             return vim.fn.input('Path to executable: ', vim.fn.getcwd() .. '/', 'file')
--         end,
--         cwd = '${workspaceFolder}',
--         stopOnEntry = false,
--         args = {},
--     },
-- }

return {}

-- dap.adapters.lldb = {
--     type = 'executable',
--     attach = {
--         pidProperty = 'pid',
--         pidSelect = 'ask',
--     },
--     command = shell.select_executable {
--         'lldb-vscode-18',
--         'lldb-vscode-17',
--         'lldb-vscode-16',
--         'lldb-vscode-15',
--         'lldb-vscode',
--     },
--     env = function()
--         local variables = {
--             LLDB_LAUNCH_FLAG_LAUNCH_IN_TTY = 'YES',
--         }
--         for k, v in pairs(vim.fn.environ()) do
--             table.insert(variables, string.format('%s=%s', k, v))
--         end
--         return variables
--     end,
--     name = 'lldb',
--     stopOnEntry = false,
--     -- initCommands =
--     -- 'command script import "/home/stephan/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/etc/lldb_lookup.py"',
-- }
